// Code generated by gen-api-sdk. DO NOT EDIT.
import type { ClientCapabilities, Implementation, JSONRPCRequest, JSONRPCResponse, RequestMeta, ServerDiscoverResult } from "./types.gen";

export class APIError extends Error {
  constructor(
    public status: number,
    public code: string,
    public details?: Record<string, unknown>,
  ) {
    super(code);
  }
}

export type FetchFn = (url: string, init?: RequestInit) => Promise<Response>;

function makeRequester(fetchFn: FetchFn) {
  return async function request<T>(method: string, path: string, body?: unknown, headers: Record<string, string> = {}): Promise<T> {
    const init: RequestInit = { method, headers: { "Content-Type": "application/json", ...headers }, signal: AbortSignal.timeout(60_000) };
    if (body !== undefined) init.body = JSON.stringify(body);
    const res = await fetchFn(path, init);
    if (!res.ok) {
      const err = (await res.json()) as JSONRPCResponse;
      const e = new APIError(res.status, String(err.error?.code ?? "UNKNOWN"), undefined);
      e.message = err.error?.message ?? "";
      throw e;
    }
    return res.json() as Promise<T>;
  };
}

// createApiClient returns an API client bound to the given fetch function.
// When fetchFn is omitted, globalThis.fetch is used.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function createApiClient(fetchFn: FetchFn = (globalThis as any).fetch.bind(globalThis)) {
  const request = makeRequester(fetchFn);
  const mcpProtocolVersion = "2026-07-28";
  let mcpId = 0;
  const mcpMeta = (): RequestMeta => ({
    "io.modelcontextprotocol/protocolVersion": mcpProtocolVersion,
    "io.modelcontextprotocol/clientInfo": { name: "mcp-typescript-sdk", version: "1.0.0" } as Implementation,
    "io.modelcontextprotocol/clientCapabilities": {} as ClientCapabilities,
  });
  const mcpRequest = async <T>(method: string, params: unknown, headers: Record<string, string> = {}): Promise<T> => {
    const resp = await request<JSONRPCResponse>("POST", "", {
      jsonrpc: "2.0",
      id: ++mcpId,
      method,
      params,
    }, {
      "Mcp-Protocol-Version": mcpProtocolVersion,
      "Mcp-Method": method,
      ...headers,
    });
    if (resp.error) throw new Error(resp.error.message);
    return resp.result as T;
  };
  const serverDiscover = (headers: Record<string, string> = {}): Promise<ServerDiscoverResult> =>
    mcpRequest<ServerDiscoverResult>("server/discover", { _meta: mcpMeta() }, headers);
  const serverInstructions = async (headers: Record<string, string> = {}): Promise<string> =>
    (await serverDiscover(headers)).instructions ?? "";
  return {
    serverDiscover,
    serverInstructions,
    /** Sends a raw MCP JSON-RPC request to the client base URL. The caller supplies required MCP transport headers. */
    mcp: (req: JSONRPCRequest, headers: Record<string, string> = {}): Promise<JSONRPCResponse> => request<JSONRPCResponse>("POST", "", req, headers),
  };
}

export type APIClient = ReturnType<typeof createApiClient>;
