// Code generated by gen-api-sdk. DO NOT EDIT.
import Foundation

public struct ApiError: Error {
    public let statusCode: Int
    public let code: String
    public let message: String
    public let details: [String: JSONValue]?
}

public final class ApiClient {
    private let baseURL: String
    private let tokenProvider: (() -> String?)?
    private let urlSession: URLSession
    private let encoder = JSONEncoder()
    private let decoder = JSONDecoder()

    public init(baseURL: String, tokenProvider: (() -> String?)? = nil) {
        self.baseURL = baseURL.hasSuffix("/") ? String(baseURL.dropLast()) : baseURL
        self.tokenProvider = tokenProvider
        self.urlSession = URLSession(configuration: .default)
    }

    private func request<T: Decodable>(_ method: String, path: String, body: Data? = nil, headers: [String: String] = [:]) async throws -> T {
        var req = URLRequest(url: URL(string: baseURL + path)!)
        req.httpMethod = method
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        for (name, value) in headers {
            req.setValue(value, forHTTPHeaderField: name)
        }
        req.timeoutInterval = 60
        if let token = tokenProvider?() {
            req.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
        }
        if let body {
            req.httpBody = body
        } else if ["POST", "PUT", "PATCH"].contains(method) {
            req.httpBody = Data()
        }
        let (data, response) = try await urlSession.data(for: req)
        let httpResponse = response as! HTTPURLResponse
        guard (200..<300).contains(httpResponse.statusCode) else {
            if let errResp = try? decoder.decode(JSONRPCResponse.self, from: data) {
                throw ApiError(statusCode: httpResponse.statusCode, code: String(errResp.error?.code ?? 0),
                               message: errResp.error?.message ?? "", details: nil)
            }
            throw ApiError(statusCode: httpResponse.statusCode, code: "UNKNOWN",
                           message: String(data: data, encoding: .utf8) ?? "", details: nil)
        }
        return try decoder.decode(T.self, from: data)
    }

    private func sseStream<T: Decodable>(path: String) -> AsyncThrowingStream<T, Error> {
        AsyncThrowingStream { continuation in
            let task = Task {
                do {
                    var req = URLRequest(url: URL(string: self.baseURL + path)!)
                    req.setValue("text/event-stream", forHTTPHeaderField: "Accept")
                    if let token = self.tokenProvider?() {
                        req.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
                    }
                    let (bytes, response) = try await self.urlSession.bytes(for: req)
                    if let httpResponse = response as? HTTPURLResponse,
                       !(200..<300).contains(httpResponse.statusCode) {
                        continuation.finish(throwing: ApiError(
                            statusCode: httpResponse.statusCode, code: "HTTP_ERROR",
                            message: "SSE connection failed with status \(httpResponse.statusCode)",
                            details: nil))
                        return
                    }
                    for try await line in bytes.lines {
                        if Task.isCancelled { break }
                        guard line.hasPrefix("data: ") else { continue }
                        let data = Data(line.dropFirst(6).utf8)
                        if let event = try? self.decoder.decode(T.self, from: data) {
                            continuation.yield(event)
                        }
                    }
                    continuation.finish()
                } catch {
                    continuation.finish(throwing: error)
                }
            }
            continuation.onTermination = { _ in task.cancel() }
        }
    }

    private func reconnectingStream<T>(_ connect: @escaping () -> AsyncThrowingStream<T, Error>) -> AsyncThrowingStream<T, Error> {
        AsyncThrowingStream { continuation in
            let task = Task {
                var delayNs: UInt64 = 500_000_000
                while !Task.isCancelled {
                    do {
                        for try await value in connect() {
                            delayNs = 500_000_000
                            continuation.yield(value)
                        }
                        continuation.finish()
                        return
                    } catch {
                        if Task.isCancelled { break }
                        try? await Task.sleep(nanoseconds: delayNs)
                        delayNs = min(delayNs * 3 / 2, 4_000_000_000)
                    }
                }
                continuation.finish()
            }
            continuation.onTermination = { _ in task.cancel() }
        }
    }

    // JSON endpoints
    /// Sends a raw MCP JSON-RPC request to the client base URL. The caller supplies required MCP transport headers.
    public func mcp(req: JSONRPCRequest, headers: [String: String] = [:]) async throws -> JSONRPCResponse {
        try await request("POST", path: "", body: try encoder.encode(req), headers: headers)
    }

    // SSE endpoints

    // Reconnecting SSE wrappers with exponential backoff
}
