// Code generated by gen-api-sdk. DO NOT EDIT.
import type { ErrorResponse } from "./types.gen";

export class APIError extends Error {
  constructor(
    public status: number,
    public code: string,
    public details?: Record<string, unknown>,
  ) {
    super(code);
  }
}

export type FetchFn = (url: string, init?: RequestInit) => Promise<Response>;

function makeRequester(fetchFn: FetchFn) {
  return async function request<T>(method: string, path: string, body?: unknown, headers: Record<string, string> = {}): Promise<T> {
    const init: RequestInit = { method, headers: { "Content-Type": "application/json", ...headers }, signal: AbortSignal.timeout(60_000) };
    if (body !== undefined) init.body = JSON.stringify(body);
    const res = await fetchFn(path, init);
    if (!res.ok) {
      const err = (await res.json()) as ErrorResponse;
      const e = new APIError(res.status, err.error, undefined);
      e.message = err.error_description ?? "";
      throw e;
    }
    return res.json() as Promise<T>;
  };
}

// createApiClient returns an API client bound to the given fetch function.
// When fetchFn is omitted, globalThis.fetch is used.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function createApiClient(fetchFn: FetchFn = (globalThis as any).fetch.bind(globalThis)) {
  const request = makeRequester(fetchFn);
  return {
  };
}

export type APIClient = ReturnType<typeof createApiClient>;
