// Code generated by gen-api-sdk. DO NOT EDIT.
/** ISO 8601 timestamp string (e.g. "2026-04-13T12:00:00Z"). */
export type ISOTimestamp = string & { readonly __brand: "ISOTimestamp" };


//////////
// source: types.go

/** AuthorizationServerMetadata is OAuth/OIDC discovery metadata. */
export interface AuthorizationServerMetadata {
  issuer: string;
  authorization_endpoint: string;
  token_endpoint: string;
  introspection_endpoint?: string;
  jwks_uri: string;
  registration_endpoint: string;
  revocation_endpoint?: string;
  end_session_endpoint?: string;
  response_types_supported: string[];
  grant_types_supported: string[];
  code_challenge_methods_supported: string[];
  token_endpoint_auth_methods_supported: string[];
  introspection_endpoint_auth_methods_supported?: string[];
  revocation_endpoint_auth_methods_supported?: string[];
  scopes_supported?: string[];
  dpop_signing_alg_values_supported?: string[];
  authorization_response_iss_parameter_supported: boolean;
  pushed_authorization_request_endpoint?: string;
  require_pushed_authorization_requests: boolean;
  client_id_metadata_document_supported?: boolean;
}

/** ProtectedResourceMetadata is OAuth 2.0 Protected Resource Metadata. */
export interface ProtectedResourceMetadata {
  resource: string;
  authorization_servers: string[];
  scopes_supported?: string[];
  resource_documentation?: string;
}

/**
 * JWK is a JSON Web Key.  For server keys (RSA), only kty/n/e/kid/use/alg
 * are populated.  For client DPoP keys, crv/x/y may also be set.
 */
export interface JWK {
  kty: string;
  use?: string;
  alg?: string;
  kid?: string;
  n?: string;
  e?: string;
  crv?: string;
  x?: string;
  y?: string;
  key_ops?: string[];
}

/** JWKSet is a JSON Web Key Set response. */
export interface JWKSet {
  keys: JWK[];
}

/** ClientIDMetadataDocument describes an OAuth client identified by its HTTPS metadata URL. */
export interface ClientIDMetadataDocument {
  client_id: string;
  client_name: string;
  redirect_uris: string[];
  token_endpoint_auth_method?: string;
  grant_types?: string[];
  response_types?: string[];
  jwks?: JWKSet;
  jwks_uri?: string;
}

/** RegisterRequest is a dynamic client registration request. */
export interface RegisterRequest {
  client_name: string;
  redirect_uris: string[];
  token_endpoint_auth_method: string;
  grant_types?: string[];
}

/** RegisterResponse is a dynamic client registration response (RFC 7592). */
export interface RegisterResponse {
  client_id: string;
  client_id_issued_at: number /* int64 */;
  client_name?: string;
  redirect_uris: string[];
  token_endpoint_auth_method: string;
  grant_types?: string[];
  registration_access_token?: string;
  registration_client_uri?: string;
}

/**
 * UpdateClientRequest is an RFC 7592 client update request body.
 * Nil pointer fields leave the corresponding client field unchanged.
 */
export interface UpdateClientRequest {
  client_name?: string;
  redirect_uris?: string[];
  token_endpoint_auth_method?: string;
  grant_types?: string[];
}

/** Token holds an OAuth 2.0 access token and associated metadata. */
export interface Token {
  AccessToken: string;
  /** e.g., "Bearer"; always set by the constructor */
  TokenType: string;
  RefreshToken: string;
  /** zero means no expiry */
  Expiry: string;
}

/** TokenResponse is an OAuth token endpoint response. */
export interface TokenResponse {
  access_token: string;
  token_type: string;
  expires_in: number /* int64 */;
  refresh_token?: string;
  scope?: string;
}

/** IntrospectionRequest is an RFC 7662 token introspection request body. */
export interface IntrospectionRequest {
  token: string;
  token_type_hint?: string;
}

/** TokenConfirmation holds key confirmation claims per RFC 9449 §6.1. */
export interface TokenConfirmation {
  jkt: string;
}

/** IntrospectionResponse is an RFC 7662 token introspection response body. */
export interface IntrospectionResponse {
  active: boolean;
  scope?: string;
  client_id?: string;
  token_type?: string;
  exp?: number /* int64 */;
  sub?: string;
  username?: string;
  iss?: string;
  aud?: string;
  iat?: number /* int64 */;
  cnf?: TokenConfirmation;
}

/** ErrorResponse is an OAuth error response body. */
export interface ErrorResponse {
  error: string;
  error_description?: string;
}

/** PARResponse is an RFC 9126 pushed authorization request response. */
export interface PARResponse {
  request_uri: string;
  expires_in: number /* int64 */;
}

/** DeviceAuthorizationRequest is an RFC 8628 device authorization request body. */
export interface DeviceAuthorizationRequest {
  client_id: string;
  scope?: string;
}

/** DeviceAuthorizationResponse is an RFC 8628 device authorization response body. */
export interface DeviceAuthorizationResponse {
  device_code: string;
  user_code: string;
  verification_uri: string;
  verification_uri_complete?: string;
  expires_in: number /* int64 */;
  interval?: number /* int64 */;
}

