// Code generated by gen-api-sdk. DO NOT EDIT.
package com.fghbuild.mcp.sdk.v1

import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.onEach
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import okhttp3.Response
import okhttp3.sse.EventSource
import okhttp3.sse.EventSourceListener
import okhttp3.sse.EventSources
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException

class ApiException(
    val statusCode: Int,
    val code: String,
    message: String,
    val details: Map<String, kotlinx.serialization.json.JsonElement>? = null,
) : Exception(message)

class ApiClient(
    baseURL: String,
    private val tokenProvider: (() -> String?)? = null,
    private val httpClient: OkHttpClient = OkHttpClient(),
) {
    private val baseURL: String = baseURL.trimEnd('/')
    private val json = Json { ignoreUnknownKeys = true }
    private val jsonMediaType = "application/json".toMediaType()
    private val mcpID = java.util.concurrent.atomic.AtomicInteger(0)

    private suspend inline fun <reified T> request(method: String, path: String, body: String? = null, headers: Map<String, String> = emptyMap()): T {
        val url = "$baseURL$path"
        val needsBody = method in listOf("POST", "PUT", "PATCH")
        val requestBody = body?.toRequestBody(jsonMediaType)
            ?: if (needsBody) "".toRequestBody(jsonMediaType) else null
        val request = Request.Builder()
            .url(url)
            .method(method, requestBody)
            .header("Content-Type", "application/json")
            .apply {
                headers.forEach { (name, value) -> header(name, value) }
                tokenProvider?.invoke()?.let { header("Authorization", "Bearer $it") }
            }
            .build()
        return suspendCancellableCoroutine { cont ->
            val call = httpClient.newCall(request)
            cont.invokeOnCancellation { call.cancel() }
            call.enqueue(object : okhttp3.Callback {
                override fun onFailure(call: okhttp3.Call, e: java.io.IOException) {
                    cont.resumeWithException(e)
                }
                override fun onResponse(call: okhttp3.Call, response: Response) {
                    response.use { resp ->
                        val responseBody = resp.body?.string() ?: ""
                        if (!resp.isSuccessful) {
                            try {
                                val err = json.decodeFromString<JSONRPCResponse>(responseBody)
                                cont.resumeWithException(
                                    ApiException(resp.code, err.error?.code?.toString() ?: "UNKNOWN", err.error?.message ?: "", null)
                                )
                            } catch (_: Exception) {
                                cont.resumeWithException(
                                    ApiException(resp.code, "UNKNOWN", responseBody)
                                )
                            }
                            return
                        }
                        try {
                            cont.resume(json.decodeFromString<T>(responseBody))
                        } catch (e: Exception) {
                            cont.resumeWithException(e)
                        }
                    }
                }
            })
        }
    }

    // JSON endpoints
    /** Sends a raw MCP JSON-RPC request to the client base URL. The caller supplies required MCP transport headers. */
    suspend fun mcp(req: JSONRPCRequest, headers: Map<String, String> = emptyMap()): JSONRPCResponse = request("POST", "", json.encodeToString(req), headers = headers)

    /** Discovers server metadata, capabilities, and instructions. */
    suspend fun serverDiscover(headers: Map<String, String> = emptyMap()): ServerDiscoverResult {
        val response = mcp(
            req = JSONRPCRequest(
                jsonrpc = "2.0",
                id = kotlinx.serialization.json.JsonPrimitive(mcpID.incrementAndGet()),
                method = Method.ServerDiscover,
                params = mcpMetaParams(),
            ),
            headers = mcpHeaders(Method.ServerDiscover, headers),
        )
        response.error?.let { error(it.message) }
        val result = response.result ?: error("Missing result in MCP response")
        return json.decodeFromString(ServerDiscoverResult.serializer(), result.toString())
    }

    /** Returns server instructions, or an empty string when none are advertised. */
    suspend fun serverInstructions(headers: Map<String, String> = emptyMap()): String =
        serverDiscover(headers).instructions.orEmpty()

    private fun mcpHeaders(method: Method, headers: Map<String, String>): Map<String, String> = buildMap {
        put("Mcp-Protocol-Version", "2026-07-28")
        put("Mcp-Method", method.value)
        putAll(headers)
    }

    private fun mcpMetaParams(): kotlinx.serialization.json.JsonObject {
        val clientInfo = kotlinx.serialization.json.JsonObject(mapOf(
            "name" to kotlinx.serialization.json.JsonPrimitive("mcp-kotlin-sdk"),
            "version" to kotlinx.serialization.json.JsonPrimitive("1.0.0"),
        ))
        val meta = kotlinx.serialization.json.JsonObject(mapOf(
            "io.modelcontextprotocol/protocolVersion" to kotlinx.serialization.json.JsonPrimitive("2026-07-28"),
            "io.modelcontextprotocol/clientInfo" to clientInfo,
            "io.modelcontextprotocol/clientCapabilities" to kotlinx.serialization.json.JsonObject(emptyMap()),
        ))
        return kotlinx.serialization.json.JsonObject(mapOf("_meta" to meta))
    }

    /** Opens a POST-based MCP subscription stream. */
    fun subscriptionsListen(
        req: JSONRPCRequest,
        headers: Map<String, String> = emptyMap(),
    ): Flow<JSONRPCNotification> = sseFlow(
        method = "POST",
        path = "",
        body = json.encodeToString(req),
        headers = headers,
    )

    // SSE endpoints

    private inline fun <reified T> sseFlow(
        path: String,
        method: String = "GET",
        body: String? = null,
        headers: Map<String, String> = emptyMap(),
    ): Flow<T> = callbackFlow {
        val requestBody = body?.toRequestBody(jsonMediaType)
        val request = Request.Builder()
            .url("$baseURL$path")
            .header("Accept", "text/event-stream")
            .apply {
                if (requestBody != null) header("Content-Type", "application/json")
                headers.forEach { (name, value) -> header(name, value) }
                tokenProvider?.invoke()?.let { header("Authorization", "Bearer $it") }
            }
            .method(method, requestBody)
            .build()
        val factory = EventSources.createFactory(httpClient)
        val source = factory.newEventSource(request, object : EventSourceListener() {
            override fun onEvent(eventSource: EventSource, id: String?, type: String?, data: String) {
                try {
                    val event = json.decodeFromString<T>(data)
                    if (trySend(event).isFailure) eventSource.cancel()
                } catch (e: Exception) {
                    close(e)
                }
            }
            override fun onFailure(eventSource: EventSource, t: Throwable?, response: Response?) {
                close(t ?: java.io.IOException("SSE connection failed: HTTP ${response?.code ?: "unknown"}"))
            }
            override fun onClosed(eventSource: EventSource) {
                close()
            }
        })
        awaitClose { source.cancel() }
    }

    // Reconnecting SSE wrappers with exponential backoff.

    private fun <T> reconnectingFlow(connect: () -> Flow<T>): Flow<T> = flow {
        var delayMs = 500L
        while (true) {
            try {
                connect().onEach { delayMs = 500L }.collect { emit(it) }
            } catch (e: CancellationException) {
                throw e
            } catch (_: Exception) {
                delay(jitteredDelay(delayMs))
                delayMs = (delayMs * 3 / 2).coerceAtMost(30_000L)
            }
        }
    }

    private fun jitteredDelay(base: Long): Long = (base * (0.75 + Math.random() * 0.5)).toLong()
}
