// Code generated by gen-api-sdk. DO NOT EDIT.
@file:UseSerializers(InstantSerializer::class)

package com.caic.oauth.sdk.v1

import java.time.Instant
import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonElement

/** Serializes [Instant] as an ISO 8601 string. */
object InstantSerializer : KSerializer<Instant> {
    override val descriptor = PrimitiveSerialDescriptor("Instant", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: Instant) = encoder.encodeString(value.toString())
    override fun deserialize(decoder: Decoder): Instant = Instant.parse(decoder.decodeString())
}

object ErrorCodes {
}

// OAuth 2.0 Authorization Server Metadata (RFC 8414)

/** AuthorizationServerMetadata is OAuth/OIDC discovery metadata. */
@Serializable
data class AuthorizationServerMetadata(
    val issuer: String,
    val authorization_endpoint: String,
    val token_endpoint: String,
    val introspection_endpoint: String? = null,
    val jwks_uri: String,
    val registration_endpoint: String,
    val revocation_endpoint: String? = null,
    val end_session_endpoint: String? = null,
    val response_types_supported: List<String>,
    val grant_types_supported: List<String>,
    val code_challenge_methods_supported: List<String>,
    val token_endpoint_auth_methods_supported: List<String>,
    val introspection_endpoint_auth_methods_supported: List<String>? = null,
    val revocation_endpoint_auth_methods_supported: List<String>? = null,
    val scopes_supported: List<String>? = null,
    val dpop_signing_alg_values_supported: List<String>? = null,
    val authorization_response_iss_parameter_supported: Boolean,
    val pushed_authorization_request_endpoint: String? = null,
    val require_pushed_authorization_requests: Boolean,
    val client_id_metadata_document_supported: Boolean? = null,
)

// OAuth 2.0 Protected Resource Metadata (RFC 9728)

/** ProtectedResourceMetadata is OAuth 2.0 Protected Resource Metadata. */
@Serializable
data class ProtectedResourceMetadata(
    val resource: String,
    val authorization_servers: List<String>,
    val scopes_supported: List<String>? = null,
    val resource_documentation: String? = null,
)

// JSON Web Key (RFC 7517)

/**
 * JWK is a JSON Web Key.  For server keys (RSA), only kty/n/e/kid/use/alg
 * are populated.  For client DPoP keys, crv/x/y may also be set.
 */
@Serializable
data class JWK(
    val kty: String,
    val use: String? = null,
    val alg: String? = null,
    val kid: String? = null,
    val n: String? = null,
    val e: String? = null,
    val crv: String? = null,
    val x: String? = null,
    val y: String? = null,
    val key_ops: List<String>? = null,
)

// JSON Web Key Set (RFC 7517)

/** JWKSet is a JSON Web Key Set response. */
@Serializable
data class JWKSet(val keys: List<JWK>)

// OAuth Client ID Metadata Document

/** ClientIDMetadataDocument describes an OAuth client identified by its HTTPS metadata URL. */
@Serializable
data class ClientIDMetadataDocument(
    val client_id: String,
    val client_name: String,
    val redirect_uris: List<String>,
    val token_endpoint_auth_method: String? = null,
    val grant_types: List<String>? = null,
    val response_types: List<String>? = null,
    val jwks: JWKSet? = null,
    val jwks_uri: String? = null,
)

// OAuth 2.0 Dynamic Client Registration request (RFC 7591)

/** RegisterRequest is a dynamic client registration request. */
@Serializable
data class RegisterRequest(
    val client_name: String,
    val redirect_uris: List<String>,
    val token_endpoint_auth_method: String,
    val grant_types: List<String>? = null,
)

// OAuth 2.0 Dynamic Client Registration response (RFC 7591, 7592)

/** RegisterResponse is a dynamic client registration response (RFC 7592). */
@Serializable
data class RegisterResponse(
    val client_id: String,
    val client_id_issued_at: Long,
    val client_name: String? = null,
    val redirect_uris: List<String>,
    val token_endpoint_auth_method: String,
    val grant_types: List<String>? = null,
    val registration_access_token: String? = null,
    val registration_client_uri: String? = null,
)

// OAuth 2.0 Dynamic Client Registration update (RFC 7592)

/**
 * UpdateClientRequest is an RFC 7592 client update request body.
 * Nil pointer fields leave the corresponding client field unchanged.
 */
@Serializable
data class UpdateClientRequest(
    val client_name: String? = null,
    val redirect_uris: List<String>? = null,
    val token_endpoint_auth_method: String? = null,
    val grant_types: List<String>? = null,
)

// OAuth 2.0 client-side access token (RFC 6749)

/** Token holds an OAuth 2.0 access token and associated metadata. */
@Serializable
data class Token(
    val AccessToken: String,
    /** e.g., "Bearer"; always set by the constructor */
    val TokenType: String,
    val RefreshToken: String,
    /** zero means no expiry */
    val Expiry: String,
)

// OAuth 2.0 token endpoint response (RFC 6749)

/** TokenResponse is an OAuth token endpoint response. */
@Serializable
data class TokenResponse(
    val access_token: String,
    val token_type: String,
    val expires_in: Long,
    val refresh_token: String? = null,
    val scope: String? = null,
)

// OAuth 2.0 Token Introspection request (RFC 7662)

/** IntrospectionRequest is an RFC 7662 token introspection request body. */
@Serializable
data class IntrospectionRequest(val token: String, val token_type_hint: String? = null)

// DPoP Token Confirmation (RFC 9449 §6.1)

/** TokenConfirmation holds key confirmation claims per RFC 9449 §6.1. */
@Serializable
data class TokenConfirmation(val jkt: String)

// OAuth 2.0 Token Introspection response (RFC 7662)

/** IntrospectionResponse is an RFC 7662 token introspection response body. */
@Serializable
data class IntrospectionResponse(
    val active: Boolean,
    val scope: String? = null,
    val client_id: String? = null,
    val token_type: String? = null,
    val exp: Long? = null,
    val sub: String? = null,
    val username: String? = null,
    val iss: String? = null,
    val aud: String? = null,
    val iat: Long? = null,
    val cnf: TokenConfirmation? = null,
)

// OAuth 2.0 error response (RFC 6749 §5.2)

/** ErrorResponse is an OAuth error response body. */
@Serializable
data class ErrorResponse(val error: String, val error_description: String? = null)

// OAuth 2.0 Pushed Authorization Request response (RFC 9126)

/** PARResponse is an RFC 9126 pushed authorization request response. */
@Serializable
data class PARResponse(val request_uri: String, val expires_in: Long)

// OAuth 2.0 Device Authorization request (RFC 8628)

/** DeviceAuthorizationRequest is an RFC 8628 device authorization request body. */
@Serializable
data class DeviceAuthorizationRequest(val client_id: String, val scope: String? = null)

// OAuth 2.0 Device Authorization response (RFC 8628)

/** DeviceAuthorizationResponse is an RFC 8628 device authorization response body. */
@Serializable
data class DeviceAuthorizationResponse(
    val device_code: String,
    val user_code: String,
    val verification_uri: String,
    val verification_uri_complete: String? = null,
    val expires_in: Long,
    val interval: Long? = null,
)

