// Code generated by gen-api-sdk. DO NOT EDIT.
@file:UseSerializers(InstantSerializer::class)

package com.caic.voicegateway.sdk.v1

import java.time.Instant
import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonElement

/** Serializes [Instant] as an ISO 8601 string. */
object InstantSerializer : KSerializer<Instant> {
    override val descriptor = PrimitiveSerialDescriptor("Instant", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: Instant) = encoder.encodeString(value.toString())
    override fun deserialize(decoder: Decoder): Instant = Instant.parse(decoder.decodeString())
}

@Serializable(with = ErrorCodeSerializer::class)
sealed interface ErrorCode {
    val value: String
    @Serializable
    data object BadRequest : ErrorCode {
        override val value = "BAD_REQUEST"
    }
    @Serializable
    data object VoiceBridgeUnavailable : ErrorCode {
        override val value = "VOICE_BRIDGE_UNAVAILABLE"
    }
    @Serializable
    data object Unauthorized : ErrorCode {
        override val value = "UNAUTHORIZED"
    }
    @Serializable
    data object VoiceOfferFailed : ErrorCode {
        override val value = "VOICE_OFFER_FAILED"
    }
    @Serializable
    data class Other(override val value: String) : ErrorCode
}

object ErrorCodeSerializer : KSerializer<ErrorCode> {
    override val descriptor = PrimitiveSerialDescriptor("ErrorCode", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: ErrorCode) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): ErrorCode {
        val v = decoder.decodeString()
        return when (v) {
            "BAD_REQUEST" -> ErrorCode.BadRequest
            "VOICE_BRIDGE_UNAVAILABLE" -> ErrorCode.VoiceBridgeUnavailable
            "UNAUTHORIZED" -> ErrorCode.Unauthorized
            "VOICE_OFFER_FAILED" -> ErrorCode.VoiceOfferFailed
            else -> ErrorCode.Other(v)
        }
    }
}

@Serializable(with = InterruptSourceSerializer::class)
sealed interface InterruptSource {
    val value: String
    @Serializable
    data object User : InterruptSource {
        override val value = "user"
    }
    @Serializable
    data object Tool : InterruptSource {
        override val value = "tool"
    }
    @Serializable
    data class Other(override val value: String) : InterruptSource
}

object InterruptSourceSerializer : KSerializer<InterruptSource> {
    override val descriptor = PrimitiveSerialDescriptor("InterruptSource", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: InterruptSource) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): InterruptSource {
        val v = decoder.decodeString()
        return when (v) {
            "user" -> InterruptSource.User
            "tool" -> InterruptSource.Tool
            else -> InterruptSource.Other(v)
        }
    }
}

@Serializable(with = MessageKindSerializer::class)
sealed interface MessageKind {
    val value: String
    @Serializable
    data object SessionSetup : MessageKind {
        override val value = "session.setup"
    }
    @Serializable
    data object ContextUpdate : MessageKind {
        override val value = "context.update"
    }
    @Serializable
    data object UserMessage : MessageKind {
        override val value = "user.message"
    }
    @Serializable
    data object ToolResult : MessageKind {
        override val value = "tool.result"
    }
    @Serializable
    data object TurnCancel : MessageKind {
        override val value = "turn.cancel"
    }
    @Serializable
    data object SessionClose : MessageKind {
        override val value = "session.close"
    }
    @Serializable
    data object SessionReady : MessageKind {
        override val value = "session.ready"
    }
    @Serializable
    data object TranscriptDelta : MessageKind {
        override val value = "transcript.delta"
    }
    @Serializable
    data object AssistantTextDelta : MessageKind {
        override val value = "assistant.text.delta"
    }
    @Serializable
    data object SpeechStarted : MessageKind {
        override val value = "speech.started"
    }
    @Serializable
    data object SpeechEnded : MessageKind {
        override val value = "speech.ended"
    }
    @Serializable
    data object ToolCall : MessageKind {
        override val value = "tool.call"
    }
    @Serializable
    data object Interrupted : MessageKind {
        override val value = "interrupted"
    }
    @Serializable
    data object Error : MessageKind {
        override val value = "error"
    }
    @Serializable
    data class Other(override val value: String) : MessageKind
}

object MessageKindSerializer : KSerializer<MessageKind> {
    override val descriptor = PrimitiveSerialDescriptor("MessageKind", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: MessageKind) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): MessageKind {
        val v = decoder.decodeString()
        return when (v) {
            "session.setup" -> MessageKind.SessionSetup
            "context.update" -> MessageKind.ContextUpdate
            "user.message" -> MessageKind.UserMessage
            "tool.result" -> MessageKind.ToolResult
            "turn.cancel" -> MessageKind.TurnCancel
            "session.close" -> MessageKind.SessionClose
            "session.ready" -> MessageKind.SessionReady
            "transcript.delta" -> MessageKind.TranscriptDelta
            "assistant.text.delta" -> MessageKind.AssistantTextDelta
            "speech.started" -> MessageKind.SpeechStarted
            "speech.ended" -> MessageKind.SpeechEnded
            "tool.call" -> MessageKind.ToolCall
            "interrupted" -> MessageKind.Interrupted
            "error" -> MessageKind.Error
            else -> MessageKind.Other(v)
        }
    }
}

@Serializable(with = SpeakerSerializer::class)
sealed interface Speaker {
    val value: String
    @Serializable
    data object User : Speaker {
        override val value = "user"
    }
    @Serializable
    data object Assistant : Speaker {
        override val value = "assistant"
    }
    @Serializable
    data class Other(override val value: String) : Speaker
}

object SpeakerSerializer : KSerializer<Speaker> {
    override val descriptor = PrimitiveSerialDescriptor("Speaker", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: Speaker) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): Speaker {
        val v = decoder.decodeString()
        return when (v) {
            "user" -> Speaker.User
            "assistant" -> Speaker.Assistant
            else -> Speaker.Other(v)
        }
    }
}

@Serializable(with = VoiceRTCConnectionStateSerializer::class)
sealed interface VoiceRTCConnectionState {
    val value: String
    @Serializable
    data object New : VoiceRTCConnectionState {
        override val value = "new"
    }
    @Serializable
    data object Connecting : VoiceRTCConnectionState {
        override val value = "connecting"
    }
    @Serializable
    data object Connected : VoiceRTCConnectionState {
        override val value = "connected"
    }
    @Serializable
    data object Disconnected : VoiceRTCConnectionState {
        override val value = "disconnected"
    }
    @Serializable
    data object Failed : VoiceRTCConnectionState {
        override val value = "failed"
    }
    @Serializable
    data object Closed : VoiceRTCConnectionState {
        override val value = "closed"
    }
    @Serializable
    data class Other(override val value: String) : VoiceRTCConnectionState
}

object VoiceRTCConnectionStateSerializer : KSerializer<VoiceRTCConnectionState> {
    override val descriptor = PrimitiveSerialDescriptor("VoiceRTCConnectionState", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: VoiceRTCConnectionState) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): VoiceRTCConnectionState {
        val v = decoder.decodeString()
        return when (v) {
            "new" -> VoiceRTCConnectionState.New
            "connecting" -> VoiceRTCConnectionState.Connecting
            "connected" -> VoiceRTCConnectionState.Connected
            "disconnected" -> VoiceRTCConnectionState.Disconnected
            "failed" -> VoiceRTCConnectionState.Failed
            "closed" -> VoiceRTCConnectionState.Closed
            else -> VoiceRTCConnectionState.Other(v)
        }
    }
}

@Serializable(with = VoiceRTCConnectivityIssueSerializer::class)
sealed interface VoiceRTCConnectivityIssue {
    val value: String
    @Serializable
    data object None : VoiceRTCConnectivityIssue {
        override val value = "none"
    }
    @Serializable
    data object VoiceBridgeUnavailable : VoiceRTCConnectivityIssue {
        override val value = "voice_bridge_unavailable"
    }
    @Serializable
    data object ServerSessionMissing : VoiceRTCConnectivityIssue {
        override val value = "server_session_missing"
    }
    @Serializable
    data object ServerICEFailed : VoiceRTCConnectivityIssue {
        override val value = "server_ice_failed"
    }
    @Serializable
    data object UDPUnreachable : VoiceRTCConnectivityIssue {
        override val value = "udp_unreachable"
    }
    @Serializable
    data object DataChannelNotOpen : VoiceRTCConnectivityIssue {
        override val value = "data_channel_not_open"
    }
    @Serializable
    data object VoiceBackendConnecting : VoiceRTCConnectivityIssue {
        override val value = "voice_backend_connecting"
    }
    @Serializable
    data object SessionReadyNotDelivered : VoiceRTCConnectivityIssue {
        override val value = "session_ready_not_delivered"
    }
    @Serializable
    data object UnknownTimeout : VoiceRTCConnectivityIssue {
        override val value = "unknown_timeout"
    }
    @Serializable
    data class Other(override val value: String) : VoiceRTCConnectivityIssue
}

object VoiceRTCConnectivityIssueSerializer : KSerializer<VoiceRTCConnectivityIssue> {
    override val descriptor = PrimitiveSerialDescriptor("VoiceRTCConnectivityIssue", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: VoiceRTCConnectivityIssue) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): VoiceRTCConnectivityIssue {
        val v = decoder.decodeString()
        return when (v) {
            "none" -> VoiceRTCConnectivityIssue.None
            "voice_bridge_unavailable" -> VoiceRTCConnectivityIssue.VoiceBridgeUnavailable
            "server_session_missing" -> VoiceRTCConnectivityIssue.ServerSessionMissing
            "server_ice_failed" -> VoiceRTCConnectivityIssue.ServerICEFailed
            "udp_unreachable" -> VoiceRTCConnectivityIssue.UDPUnreachable
            "data_channel_not_open" -> VoiceRTCConnectivityIssue.DataChannelNotOpen
            "voice_backend_connecting" -> VoiceRTCConnectivityIssue.VoiceBackendConnecting
            "session_ready_not_delivered" -> VoiceRTCConnectivityIssue.SessionReadyNotDelivered
            "unknown_timeout" -> VoiceRTCConnectivityIssue.UnknownTimeout
            else -> VoiceRTCConnectivityIssue.Other(v)
        }
    }
}

@Serializable(with = VoiceRTCConnectivitySideSerializer::class)
sealed interface VoiceRTCConnectivitySide {
    val value: String
    @Serializable
    data object None : VoiceRTCConnectivitySide {
        override val value = "none"
    }
    @Serializable
    data object Server : VoiceRTCConnectivitySide {
        override val value = "server"
    }
    @Serializable
    data object Client : VoiceRTCConnectivitySide {
        override val value = "client"
    }
    @Serializable
    data object Network : VoiceRTCConnectivitySide {
        override val value = "network"
    }
    @Serializable
    data object Unknown : VoiceRTCConnectivitySide {
        override val value = "unknown"
    }
    @Serializable
    data class Other(override val value: String) : VoiceRTCConnectivitySide
}

object VoiceRTCConnectivitySideSerializer : KSerializer<VoiceRTCConnectivitySide> {
    override val descriptor = PrimitiveSerialDescriptor("VoiceRTCConnectivitySide", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: VoiceRTCConnectivitySide) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): VoiceRTCConnectivitySide {
        val v = decoder.decodeString()
        return when (v) {
            "none" -> VoiceRTCConnectivitySide.None
            "server" -> VoiceRTCConnectivitySide.Server
            "client" -> VoiceRTCConnectivitySide.Client
            "network" -> VoiceRTCConnectivitySide.Network
            "unknown" -> VoiceRTCConnectivitySide.Unknown
            else -> VoiceRTCConnectivitySide.Other(v)
        }
    }
}

@Serializable(with = VoiceRTCDataChannelStateSerializer::class)
sealed interface VoiceRTCDataChannelState {
    val value: String
    @Serializable
    data object New : VoiceRTCDataChannelState {
        override val value = "new"
    }
    @Serializable
    data object Connecting : VoiceRTCDataChannelState {
        override val value = "connecting"
    }
    @Serializable
    data object Open : VoiceRTCDataChannelState {
        override val value = "open"
    }
    @Serializable
    data object Closing : VoiceRTCDataChannelState {
        override val value = "closing"
    }
    @Serializable
    data object Closed : VoiceRTCDataChannelState {
        override val value = "closed"
    }
    @Serializable
    data class Other(override val value: String) : VoiceRTCDataChannelState
}

object VoiceRTCDataChannelStateSerializer : KSerializer<VoiceRTCDataChannelState> {
    override val descriptor = PrimitiveSerialDescriptor("VoiceRTCDataChannelState", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: VoiceRTCDataChannelState) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): VoiceRTCDataChannelState {
        val v = decoder.decodeString()
        return when (v) {
            "new" -> VoiceRTCDataChannelState.New
            "connecting" -> VoiceRTCDataChannelState.Connecting
            "open" -> VoiceRTCDataChannelState.Open
            "closing" -> VoiceRTCDataChannelState.Closing
            "closed" -> VoiceRTCDataChannelState.Closed
            else -> VoiceRTCDataChannelState.Other(v)
        }
    }
}

@Serializable(with = VoiceRTCICEConnectionStateSerializer::class)
sealed interface VoiceRTCICEConnectionState {
    val value: String
    @Serializable
    data object New : VoiceRTCICEConnectionState {
        override val value = "new"
    }
    @Serializable
    data object Checking : VoiceRTCICEConnectionState {
        override val value = "checking"
    }
    @Serializable
    data object Connected : VoiceRTCICEConnectionState {
        override val value = "connected"
    }
    @Serializable
    data object Completed : VoiceRTCICEConnectionState {
        override val value = "completed"
    }
    @Serializable
    data object Disconnected : VoiceRTCICEConnectionState {
        override val value = "disconnected"
    }
    @Serializable
    data object Failed : VoiceRTCICEConnectionState {
        override val value = "failed"
    }
    @Serializable
    data object Closed : VoiceRTCICEConnectionState {
        override val value = "closed"
    }
    @Serializable
    data class Other(override val value: String) : VoiceRTCICEConnectionState
}

object VoiceRTCICEConnectionStateSerializer : KSerializer<VoiceRTCICEConnectionState> {
    override val descriptor = PrimitiveSerialDescriptor("VoiceRTCICEConnectionState", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: VoiceRTCICEConnectionState) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): VoiceRTCICEConnectionState {
        val v = decoder.decodeString()
        return when (v) {
            "new" -> VoiceRTCICEConnectionState.New
            "checking" -> VoiceRTCICEConnectionState.Checking
            "connected" -> VoiceRTCICEConnectionState.Connected
            "completed" -> VoiceRTCICEConnectionState.Completed
            "disconnected" -> VoiceRTCICEConnectionState.Disconnected
            "failed" -> VoiceRTCICEConnectionState.Failed
            "closed" -> VoiceRTCICEConnectionState.Closed
            else -> VoiceRTCICEConnectionState.Other(v)
        }
    }
}

@Serializable(with = VoiceRTCICEGatheringStateSerializer::class)
sealed interface VoiceRTCICEGatheringState {
    val value: String
    @Serializable
    data object New : VoiceRTCICEGatheringState {
        override val value = "new"
    }
    @Serializable
    data object Gathering : VoiceRTCICEGatheringState {
        override val value = "gathering"
    }
    @Serializable
    data object Complete : VoiceRTCICEGatheringState {
        override val value = "complete"
    }
    @Serializable
    data class Other(override val value: String) : VoiceRTCICEGatheringState
}

object VoiceRTCICEGatheringStateSerializer : KSerializer<VoiceRTCICEGatheringState> {
    override val descriptor = PrimitiveSerialDescriptor("VoiceRTCICEGatheringState", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: VoiceRTCICEGatheringState) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): VoiceRTCICEGatheringState {
        val v = decoder.decodeString()
        return when (v) {
            "new" -> VoiceRTCICEGatheringState.New
            "gathering" -> VoiceRTCICEGatheringState.Gathering
            "complete" -> VoiceRTCICEGatheringState.Complete
            else -> VoiceRTCICEGatheringState.Other(v)
        }
    }
}

@Serializable(with = VoiceRTCSignalingStateSerializer::class)
sealed interface VoiceRTCSignalingState {
    val value: String
    @Serializable
    data object Stable : VoiceRTCSignalingState {
        override val value = "stable"
    }
    @Serializable
    data object HaveLocalOffer : VoiceRTCSignalingState {
        override val value = "have-local-offer"
    }
    @Serializable
    data object HaveRemoteOffer : VoiceRTCSignalingState {
        override val value = "have-remote-offer"
    }
    @Serializable
    data object HaveLocalPranswer : VoiceRTCSignalingState {
        override val value = "have-local-pranswer"
    }
    @Serializable
    data object HaveRemotePranswer : VoiceRTCSignalingState {
        override val value = "have-remote-pranswer"
    }
    @Serializable
    data object Closed : VoiceRTCSignalingState {
        override val value = "closed"
    }
    @Serializable
    data class Other(override val value: String) : VoiceRTCSignalingState
}

object VoiceRTCSignalingStateSerializer : KSerializer<VoiceRTCSignalingState> {
    override val descriptor = PrimitiveSerialDescriptor("VoiceRTCSignalingState", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: VoiceRTCSignalingState) = encoder.encodeString(value.value)
    override fun deserialize(decoder: Decoder): VoiceRTCSignalingState {
        val v = decoder.decodeString()
        return when (v) {
            "stable" -> VoiceRTCSignalingState.Stable
            "have-local-offer" -> VoiceRTCSignalingState.HaveLocalOffer
            "have-remote-offer" -> VoiceRTCSignalingState.HaveRemoteOffer
            "have-local-pranswer" -> VoiceRTCSignalingState.HaveLocalPranswer
            "have-remote-pranswer" -> VoiceRTCSignalingState.HaveRemotePranswer
            "closed" -> VoiceRTCSignalingState.Closed
            else -> VoiceRTCSignalingState.Other(v)
        }
    }
}

/** ServiceAuthorization identifies the host and carries its scoped gateway token. */
@Serializable
data class ServiceAuthorization(
    val kind: String,
    @SerialName("instanceID") val instanceID: String,
    @SerialName("baseURL") val baseURL: String,
    val token: String,
)

/** VoiceRTCOfferReq is the request body for POST /api/voicegateway/v1/voice/rtc/offer. */
@Serializable
data class VoiceRTCOfferReq(
    /** SDP is the browser/client WebRTC offer session description from RTCSessionDescription.sdp after createOffer and setLocalDescription. */
    val sdp: String,
    /** Service authorizes a session on a standalone gateway. Embedded gateways use host authentication. */
    val service: ServiceAuthorization? = null,
)

/** VoiceRTCAnswerResp is the response for POST /api/voicegateway/v1/voice/rtc/offer. */
@Serializable
data class VoiceRTCAnswerResp(
    /** SDP is the gateway WebRTC answer session description to pass to setRemoteDescription with type "answer". */
    val sdp: String,
    /** SessionID identifies the voice RTC session for diagnostics and close calls. */
    @SerialName("sessionID") val sessionID: String,
)

/** VoiceRTCClientDiagnostics reports client-observed WebRTC state for diagnosis. */
@Serializable
data class VoiceRTCClientDiagnostics(
    /** ICEConnectionState is the client's RTCPeerConnection.iceConnectionState. */
    val iceConnectionState: VoiceRTCICEConnectionState? = null,
    /** ICEGatheringState is the client's RTCPeerConnection.iceGatheringState. */
    val iceGatheringState: VoiceRTCICEGatheringState? = null,
    /** ConnectionState is the client's RTCPeerConnection.connectionState. */
    val connectionState: VoiceRTCConnectionState? = null,
    /** SignalingState is the client's RTCPeerConnection.signalingState. */
    val signalingState: VoiceRTCSignalingState? = null,
    /** DataChannelState is the client's voice-gateway RTCDataChannel.readyState. */
    val dataChannelState: VoiceRTCDataChannelState? = null,
)

/** VoiceRTCDiagnosticsReq is the request body for POST /api/voicegateway/v1/voice/rtc/{sessionID}/diagnostics. */
@Serializable
data class VoiceRTCDiagnosticsReq(
    /** Client contains the browser/client WebRTC state observed by the caller. */
    val client: VoiceRTCClientDiagnostics? = null,
)

/** VoiceRTCUDPEndpoint reports one server UDP candidate for diagnosis. */
@Serializable
data class VoiceRTCUDPEndpoint(
    /** Host is an IP address advertised in the gateway SDP answer. */
    val host: String,
    /** Port is the UDP port paired with host in the gateway SDP answer. */
    val port: Int,
)

/** VoiceRTCServerDiagnostics reports server-observed WebRTC state for diagnosis. */
@Serializable
data class VoiceRTCServerDiagnostics(
    /** SessionFound reports whether the gateway still has the requested session. */
    val sessionFound: Boolean,
    /** UDPEndpoints are the LAN/Tailscale and optional UPnP public UDP candidates advertised to the client. */
    val udpEndpoints: List<VoiceRTCUDPEndpoint>? = null,
    /** UDPMappingError is the last UPnP mapping or refresh error, if any. */
    val udpMappingError: String? = null,
    /** ICEConnectionState is the gateway PeerConnection ICE connection state. */
    val iceConnectionState: VoiceRTCICEConnectionState? = null,
    /** ICEGatheringState is the gateway PeerConnection ICE gathering state. */
    val iceGatheringState: VoiceRTCICEGatheringState? = null,
    /** ConnectionState is the gateway PeerConnection aggregate connection state. */
    val connectionState: VoiceRTCConnectionState? = null,
    /** SignalingState is the gateway PeerConnection signaling state. */
    val signalingState: VoiceRTCSignalingState? = null,
    /** DataChannelState is the gateway-observed voice data channel state. */
    val dataChannelState: VoiceRTCDataChannelState? = null,
    /** DataChannelOpened reports whether the voice data channel reached open. */
    val dataChannelOpened: Boolean? = null,
    /** AudioTrackReceived reports whether the gateway received the client's microphone track. */
    val audioTrackReceived: Boolean? = null,
    /** BackendConnected reports whether the gateway connected to the configured voice backend. */
    val backendConnected: Boolean? = null,
    /** SessionReadySent reports whether the gateway sent session.ready to the client. */
    val sessionReadySent: Boolean? = null,
    /** LastError is the last gateway error sent to the client, if any. */
    val lastError: String? = null,
)

/** VoiceRTCDiagnosticsResp reports structured WebRTC connectivity diagnostics. */
@Serializable
data class VoiceRTCDiagnosticsResp(
    /** SessionID is the diagnosed voice RTC session ID. */
    @SerialName("sessionID") val sessionID: String,
    /** Issue is the machine-readable connectivity diagnosis. */
    val issue: VoiceRTCConnectivityIssue,
    /** Side identifies where the issue appears to be. */
    val side: VoiceRTCConnectivitySide,
    /** Message is a human-readable explanation of the diagnosis. */
    val message: String,
    /** Server contains gateway-observed WebRTC state. */
    val server: VoiceRTCServerDiagnostics,
    /** Client echoes the client diagnostics included in the request. */
    val client: VoiceRTCClientDiagnostics? = null,
)

/** StatusResp is a common response for mutation endpoints. */
@Serializable
data class StatusResp(
    /** Status is a short human-readable result such as "closed". */
    val status: String,
)

@Serializable
data class ErrorDetails(val code: ErrorCode, val message: String)

@Serializable
data class ErrorResponse(val error: ErrorDetails, val details: Map<String, JsonElement>? = null)

/** MessageEnvelope carries the kind used to dispatch data-channel messages. */
@Serializable
data class MessageEnvelope(
    /** Kind is the message discriminator used to decode the concrete message type. */
    val kind: MessageKind,
)

/** VoiceConfig describes provider-neutral voice preferences. */
@Serializable
data class VoiceConfig(
    /** Name is the requested provider-specific voice name. */
    val name: String,
    /** Language is the requested BCP 47 language tag, such as "en" or "fr-CA". */
    val language: String,
)

/** ToolDeclaration is a provider-neutral service tool declaration. */
@Serializable
data class ToolDeclaration(
    /** Name is the tool name the assistant uses in tool.call messages. */
    val name: String,
    /** Description explains when and how the assistant should use the tool. */
    val description: String,
    /** Parameters is a JSON Schema object describing the tool arguments. */
    val parameters: JsonElement,
)

/** Context carries provider-neutral text or instruction context. */
@Serializable
data class Context(
    /** SystemInstruction is provider-neutral instruction text for the assistant. */
    val systemInstruction: String? = null,
    /** Text is additional conversational context for the session. */
    val text: String? = null,
)

/** SessionSetup is the client message that initializes a voice session. */
@Serializable
data class SessionSetup(
    /** Kind must be "session.setup". */
    val kind: MessageKind,
    /** Voice contains the requested voice and language. */
    val voice: VoiceConfig,
    /** Tools declares the client-side tools the assistant may call. */
    val tools: List<ToolDeclaration>,
    /** Context provides initial instructions or text context for the session. */
    val context: Context,
)

/** ContextUpdate is a client message that appends session context. */
@Serializable
data class ContextUpdate(
    /** Kind must be "context.update". */
    val kind: MessageKind,
    /** Context contains the instructions or text to append. */
    val context: Context,
)

/** UserMessage is a client message that appends completed user text and asks the assistant to respond. */
@Serializable
data class UserMessage(
    /** Kind must be "user.message". */
    val kind: MessageKind,
    /** Text is the completed user utterance to send to the assistant. */
    val text: String,
)

/** ToolResult is a client message that returns a tool execution result. */
@Serializable
data class ToolResult(
    /** Kind must be "tool.result". */
    val kind: MessageKind,
    /** ID matches the tool.call ID being answered. */
    val id: String,
    /** Name is the tool name that produced the result. */
    val name: String,
    /** Result is the JSON result returned to the assistant. */
    val result: JsonElement,
)

/** TurnCancel is a client message that cancels the current turn. */
@Serializable
data class TurnCancel(
    /** Kind must be "turn.cancel". */
    val kind: MessageKind,
    /** Reason optionally explains why the current assistant turn was cancelled. */
    val reason: String? = null,
)

/** SessionClose is a client message that closes the voice session. */
@Serializable
data class SessionClose(
    /** Kind must be "session.close". */
    val kind: MessageKind,
    /** Reason optionally explains why the client closed the session. */
    val reason: String? = null,
)

/** SessionReady is a gateway message that reports the session is ready. */
@Serializable
data class SessionReady(
    /** Kind is "session.ready". */
    val kind: MessageKind,
)

/** TranscriptDelta is a gateway message that streams transcript text. */
@Serializable
data class TranscriptDelta(
    /** Kind is "transcript.delta". */
    val kind: MessageKind,
    /** Speaker identifies who produced this transcript text. */
    val speaker: Speaker,
    /** Text is an incremental transcript fragment. */
    val text: String,
)

/** AssistantTextDelta is a gateway message that streams assistant text. */
@Serializable
data class AssistantTextDelta(
    /** Kind is "assistant.text.delta". */
    val kind: MessageKind,
    /** Text is an incremental assistant text fragment. */
    val text: String,
)

/** SpeechStarted is a gateway message that reports speech output started. */
@Serializable
data class SpeechStarted(
    /** Kind is "speech.started". */
    val kind: MessageKind,
    /** Speaker identifies whose speech output started. */
    val speaker: Speaker,
)

/** SpeechEnded is a gateway message that reports speech output ended. */
@Serializable
data class SpeechEnded(
    /** Kind is "speech.ended". */
    val kind: MessageKind,
    /** Speaker identifies whose speech output ended. */
    val speaker: Speaker,
)

/** ToolCall is a gateway message that asks the client to execute a tool. */
@Serializable
data class ToolCall(
    /** Kind is "tool.call". */
    val kind: MessageKind,
    /** ID uniquely identifies this tool call for the matching tool.result. */
    val id: String,
    /** Name is the requested tool name. */
    val name: String,
    /** Args is the JSON argument object for the requested tool. */
    val args: JsonElement,
)

/** Interrupted is a gateway message that reports an interruption. */
@Serializable
data class Interrupted(
    /** Kind is "interrupted". */
    val kind: MessageKind,
    /** Source identifies what interrupted the turn. */
    val source: InterruptSource,
    /** Message optionally provides more detail about the interruption. */
    val message: String? = null,
)

/** Error is a gateway message that reports an error. */
@Serializable
data class Error(
    /** Kind is "error". */
    val kind: MessageKind,
    /** Message is a human-readable error description. */
    val message: String,
    /** Recoverable reports whether the client may continue using the session. */
    val recoverable: Boolean,
)

