// Code generated by gen-api-sdk. DO NOT EDIT.
import Foundation

/// ISO 8601 timestamp string (e.g. "2026-04-13T12:00:00Z").
public typealias ISOTimestamp = String

/// A Codable representation of an arbitrary JSON value.
public enum JSONValue: Codable, Equatable {
    case string(String)
    case number(Double)
    case bool(Bool)
    case object([String: JSONValue])
    case array([JSONValue])
    case null

    public init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if c.decodeNil() { self = .null; return }
        if let v = try? c.decode(Bool.self) { self = .bool(v); return }
        if let v = try? c.decode(Double.self) { self = .number(v); return }
        if let v = try? c.decode(String.self) { self = .string(v); return }
        if let v = try? c.decode([String: JSONValue].self) { self = .object(v); return }
        if let v = try? c.decode([JSONValue].self) { self = .array(v); return }
        throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown JSON value"))
    }

    public func encode(to encoder: Encoder) throws {
        var c = encoder.singleValueContainer()
        switch self {
        case .string(let v): try c.encode(v)
        case .number(let v): try c.encode(v)
        case .bool(let v): try c.encode(v)
        case .object(let v): try c.encode(v)
        case .array(let v): try c.encode(v)
        case .null: try c.encodeNil()
        }
    }
}

public enum ErrorCodes {
}

// OAuth 2.0 Authorization Server Metadata (RFC 8414)

/// AuthorizationServerMetadata is OAuth/OIDC discovery metadata.
public struct AuthorizationServerMetadata: Codable {
    public let issuer: String
    public let authorization_endpoint: String
    public let token_endpoint: String
    public let introspection_endpoint: String?
    public let jwks_uri: String
    public let registration_endpoint: String
    public let revocation_endpoint: String?
    public let end_session_endpoint: String?
    public let response_types_supported: [String]
    public let grant_types_supported: [String]
    public let code_challenge_methods_supported: [String]
    public let token_endpoint_auth_methods_supported: [String]
    public let introspection_endpoint_auth_methods_supported: [String]?
    public let revocation_endpoint_auth_methods_supported: [String]?
    public let scopes_supported: [String]?
    public let dpop_signing_alg_values_supported: [String]?
    public let authorization_response_iss_parameter_supported: Bool
    public let pushed_authorization_request_endpoint: String?
    public let require_pushed_authorization_requests: Bool
    public let client_id_metadata_document_supported: Bool?
}

// OAuth 2.0 Protected Resource Metadata (RFC 9728)

/// ProtectedResourceMetadata is OAuth 2.0 Protected Resource Metadata.
public struct ProtectedResourceMetadata: Codable {
    public let resource: String
    public let authorization_servers: [String]
    public let scopes_supported: [String]?
    public let resource_documentation: String?
}

// JSON Web Key (RFC 7517)

/// JWK is a JSON Web Key.  For server keys (RSA), only kty/n/e/kid/use/alg
/// are populated.  For client DPoP keys, crv/x/y may also be set.
public struct JWK: Codable {
    public let kty: String
    public let use: String?
    public let alg: String?
    public let kid: String?
    public let n: String?
    public let e: String?
    public let crv: String?
    public let x: String?
    public let y: String?
    public let key_ops: [String]?
}

// JSON Web Key Set (RFC 7517)

/// JWKSet is a JSON Web Key Set response.
public struct JWKSet: Codable {
    public let keys: [JWK]
}

// OAuth Client ID Metadata Document

/// ClientIDMetadataDocument describes an OAuth client identified by its HTTPS metadata URL.
public struct ClientIDMetadataDocument: Codable {
    public let client_id: String
    public let client_name: String
    public let redirect_uris: [String]
    public let token_endpoint_auth_method: String?
    public let grant_types: [String]?
    public let response_types: [String]?
    public let jwks: JWKSet?
    public let jwks_uri: String?
}

// OAuth 2.0 Dynamic Client Registration request (RFC 7591)

/// RegisterRequest is a dynamic client registration request.
public struct RegisterRequest: Codable {
    public let client_name: String
    public let redirect_uris: [String]
    public let token_endpoint_auth_method: String
    public let grant_types: [String]?
}

// OAuth 2.0 Dynamic Client Registration response (RFC 7591, 7592)

/// RegisterResponse is a dynamic client registration response (RFC 7592).
public struct RegisterResponse: Codable {
    public let client_id: String
    public let client_id_issued_at: Int
    public let client_name: String?
    public let redirect_uris: [String]
    public let token_endpoint_auth_method: String
    public let grant_types: [String]?
    public let registration_access_token: String?
    public let registration_client_uri: String?
}

// OAuth 2.0 Dynamic Client Registration update (RFC 7592)

/// UpdateClientRequest is an RFC 7592 client update request body.
/// Nil pointer fields leave the corresponding client field unchanged.
public struct UpdateClientRequest: Codable {
    public let client_name: String?
    public let redirect_uris: [String]?
    public let token_endpoint_auth_method: String?
    public let grant_types: [String]?
}

// OAuth 2.0 client-side access token (RFC 6749)

/// Token holds an OAuth 2.0 access token and associated metadata.
public struct Token: Codable {
    public let AccessToken: String
    /// e.g., "Bearer"; always set by the constructor
    public let TokenType: String
    public let RefreshToken: String
    /// zero means no expiry
    public let Expiry: String
}

// OAuth 2.0 token endpoint response (RFC 6749)

/// TokenResponse is an OAuth token endpoint response.
public struct TokenResponse: Codable {
    public let access_token: String
    public let token_type: String
    public let expires_in: Int
    public let refresh_token: String?
    public let scope: String?
}

// OAuth 2.0 Token Introspection request (RFC 7662)

/// IntrospectionRequest is an RFC 7662 token introspection request body.
public struct IntrospectionRequest: Codable {
    public let token: String
    public let token_type_hint: String?
}

// DPoP Token Confirmation (RFC 9449 §6.1)

/// TokenConfirmation holds key confirmation claims per RFC 9449 §6.1.
public struct TokenConfirmation: Codable {
    public let jkt: String
}

// OAuth 2.0 Token Introspection response (RFC 7662)

/// IntrospectionResponse is an RFC 7662 token introspection response body.
public struct IntrospectionResponse: Codable {
    public let active: Bool
    public let scope: String?
    public let client_id: String?
    public let token_type: String?
    public let exp: Int?
    public let sub: String?
    public let username: String?
    public let iss: String?
    public let aud: String?
    public let iat: Int?
    public let cnf: TokenConfirmation?
}

// OAuth 2.0 error response (RFC 6749 §5.2)

/// ErrorResponse is an OAuth error response body.
public struct ErrorResponse: Codable {
    public let error: String
    public let error_description: String?
}

// OAuth 2.0 Pushed Authorization Request response (RFC 9126)

/// PARResponse is an RFC 9126 pushed authorization request response.
public struct PARResponse: Codable {
    public let request_uri: String
    public let expires_in: Int
}

// OAuth 2.0 Device Authorization request (RFC 8628)

/// DeviceAuthorizationRequest is an RFC 8628 device authorization request body.
public struct DeviceAuthorizationRequest: Codable {
    public let client_id: String
    public let scope: String?
}

// OAuth 2.0 Device Authorization response (RFC 8628)

/// DeviceAuthorizationResponse is an RFC 8628 device authorization response body.
public struct DeviceAuthorizationResponse: Codable {
    public let device_code: String
    public let user_code: String
    public let verification_uri: String
    public let verification_uri_complete: String?
    public let expires_in: Int
    public let interval: Int?
}

